// @test error

fn foo(int x, int y)
{
	return x + y;
}

fn main()
{
	return foo(4);
}