// @test error

fn foo(int x) : int
{
	return x;
}

fn main() : int
{
	return foo(4, 4);
}