// @test error

fn foo() : int
{
	return 3;
}