// @test error

fn foo()
{
	return 3;
}