// @test error

fn foo(int x)
{
	int x = 9;
	return x;
}

fn main()
{
	return foo(4);
}